### ISSUE TITLE
Incompatible with msal4j 1.4.0 ClientCredentialFactory

### ISSUE THREAD

**Issue by vishalmasih** [microsoft/azure-spring-boot#865]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8
  
## Summary
azure-active-directory-spring-boot-starter version 2.2.3 does not work with msal4j 1.4.0 when conditional access policy is in place.

## Reproduce steps
Update the pom file as below:
```
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-active-directory-spring-boot-starter</artifactId>
			<version>2.2.3</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>0.5.0-preview</version>
		</dependency>
```
And include conditional access policy code:
```
    	final ClientRegistrationRepository clientRegistrationRepository =
                applicationContext.getBean(ClientRegistrationRepository.class);
    	http
        .authorizeRequests()
        .antMatchers("/css/**","/js/**","/logout","/images/**","/loggedout","/favicon.ico").permitAll()
        .anyRequest().authenticated()
        .and()
        .oauth2Login()
        .userInfoEndpoint()
        .oidcUserService(oidcUserService) // lines below are for conditional access policy
        .and()
        .authorizationEndpoint()
        .authorizationRequestResolver(
                new AADOAuth2AuthorizationRequestResolver(clientRegistrationRepository))
        .and()
        .failureHandler(new AADAuthenticationFailureHandler())
        ; 
```

## Expected Results
Should work without errors, User should be able to successfully login.

## Actual Results
Get this method not found exception:
```
java.lang.NoSuchMethodError: com.microsoft.aad.msal4j.ClientCredentialFactory.create(Ljava/lang/String;)Lcom/microsoft/aad/msal4j/IClientCredential;
        at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.acquireTokenForGraphApi(AzureADGraphClient.java:194) ~[azure-spring-boot-2.2.3.jar!/:na]
```

The current version of ClientCredentialFactory doesn't have a create(java.lang.String) method.

**Comment by saragluna** [comment]
Sorry for the late response. 

We're now using `0.5.0-preview` version for MSAL, do you specify `1.4.0` in your pom file?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
